version: '3.8'
services:
  app:
    build: .
    container_name: saas-platform-app
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    volumes:
      - ./:/app
    working_dir: /app
    command: npm run start
#  db:
#    image: postgres:15
#    environment:
#      POSTGRES_USER: user
#      POSTGRES_PASSWORD: password
#      POSTGRES_DB: saasdb
#    ports:
#      - '5432:5432'
#    volumes:
#      - pgdata:/var/lib/postgresql/data
#volumes:
#  pgdata: 